/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "background": "#f9fbea",
        "on-surface-variant": "#434937",
        "surface-bright": "#f9fbea",
        "on-tertiary-fixed": "#291135",
        "surface-dim": "#d9dccb",
        "tertiary": "#70547c",
        "primary": "#486800",
        "on-primary-fixed": "#131f00",
        "inverse-surface": "#2e3227",
        "tertiary-container": "#f3d0ff",
        "primary-container": "#b8ed55",
        "surface-container-high": "#e7ead9",
        "surface": "#f9fbea",
        "on-tertiary-fixed-variant": "#573d63",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#474747",
        "surface-container-highest": "#e2e4d4",
        "inverse-on-surface": "#f0f2e2",
        "outline-variant": "#c3c9b1",
        "inverse-primary": "#a3d741",
        "tertiary-fixed-dim": "#ddbbe9",
        "on-primary-fixed-variant": "#364e00",
        "on-tertiary": "#ffffff",
        "primary-hover": "#a5d944",
        "on-error": "#ffffff",
        "on-background": "#1a1d13",
        "on-primary-container": "#4a6a00",
        "primary-fixed-dim": "#a3d741",
        "on-error-container": "#93000a",
        "secondary-container": "#e2e2e2",
        "on-secondary": "#ffffff",
        "surface-variant": "#e2e4d4",
        "on-secondary-fixed": "#1b1b1b",
        "primary-fixed": "#bef45b",
        "surface-2": "#eaf5d4",
        "tertiary-fixed": "#f6d9ff",
        "outline": "#737a65",
        "surface-container": "#edefdf",
        "secondary-fixed": "#e2e2e2",
        "on-secondary-container": "#646464",
        "surface-tint": "#486800",
        "secondary-fixed-dim": "#c6c6c6",
        "surface-container-low": "#f3f5e4",
        "secondary": "#5e5e5e",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#72567e",
        "text-secondary": "#374151",
        "surface-container-lowest": "#ffffff",
        "text-muted": "#6b7280",
        "surface-hover": "#f9fafb",
        "on-surface": "#1a1d13",
        "error-container": "#ffdad6",
        "primary-subtle": "#eaf5d4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "2rem",
        base: "8",
        gutter: "1rem",
        "card-padding": "2rem",
        "section-gap": "4rem",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["1.125rem", { lineHeight: "1.6", fontWeight: "500" }],
        label: ["0.75rem", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["2.25rem", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["0.875rem", { lineHeight: "1.55", fontWeight: "500" }],
        display: ["3rem", { lineHeight: "1.05", letterSpacing: "-0.025em", fontWeight: "800" }],
        caption: ["0.75rem", { lineHeight: "1.35", fontWeight: "500" }],
        "headline-md": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "700" }],
        "body-sm": ["0.75rem", { lineHeight: "1.5", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
